### PR TITLE
Speech command eval

### PR DESCRIPTION
**Pull request by jorshi**
Top-1 error evaluation on test ground truth labels and random frame-wise predictions.

### CODE REVIEW

**Review by turian — APPROVED** [review]
Right now, since we're switching to framewise vs scenewise embeddings, I don't think we can accept this unless it's reworked. @jorshi thoughts?

**Comment by turian** [comment]
OOf didn't mean to accept this :\ not sure how to undo that

**Comment by jorshi** [comment]
@turian -- ya this needs to be updated to handle scene predictions

**Comment by jorshi** [comment]
Implemented in #143

**Pull request closed without merging**
